package org.usfirst.frc.team1885.robot.input;

public enum Sensor {
	JOYSTICK_LEFT, JOYSTICK_RIGHT, DRIVE_TRAIN_LEFT_ENCODER, DRIVE_TRAIN_RIGHT_ENCODER, RECYCLE_BIN_LEFT_ECONDER,
	RECYCLE_BIN_RIGHT_ENCODER, TOTE_LEFT_ENCODER, TOTE_RIGHT_ENCODER, TOTE_LEFT_LIMIT_SWITCH, TOTE_RIGHT_LIMIT_SWITCH
}
