package org.usfirst.frc.team1885.robot.common.type;

public enum RobotButtonType {
	INTAKE_IN,
	INTAKE_OUT,
	NUDGE,
	RIGHT_DRIFT,
	LEFT_DRIFT,
	CANCEL_AUTOMATION,
    SHOOTER_OUT,
    FLYWHEEL_IN,
    FLYWHEEL_OUT,
    SHOOTER_TWIST,
    SHOOTER_TILT,
	ARM_MOVE_X,
	ARM_MOVE_Y,
	RESET_BUTTON, 
	INCREMENT_ARM_LEFT, 
	INCREMENT_ARM_DOWN, 
	INCREMENT_ARM_RIGHT, 
	INCREMENT_ARM_UP
}
