package org.usfirst.frc.team1885.robot.common.type;

public enum RobotButtonType {
	INTAKE_IN,
	INTAKE_OUT,
	INTAKE_SOLENOID,
	NUDGE,
	RIGHT_DRIFT,
	LEFT_DRIFT,
	CANCEL_AUTOMATION,
	SHOOTER_OUT,
	ARM_JOINT_A_CLOCK,
	ARM_JOINT_A_COUNTER,
	ARM_JOINT_B_CLOCK,
	ARM_JOINT_B_COUNTER, 
	GEAR_SHIFT
}
