package org.usfirst.frc.team1885.robot.common.type;

public enum RobotButtonType {
	TOTE_LIFT,
	RECYCLE_BIN_LIFT_UP,
	RECYCLE_BIN_LIFT_DOWN,
	TOTE_LIFT_PICKUP,
	TOTE_LIFT_RELEASE,
	RECYCLE_BIN_LIFT_PICKUP,
	RECYCLE_BIN_LIFT_RELEASE,
	TOTE_LIFT_INCREMENT,
	TOTE_LIFT_DECREMENT,
	GEAR_SHIFT, 
	HARD_STOP, 
	WRIST_ROTATION,
	WRIST_EXTENSION,
	CLAW,
	TOTE_LIFT_TEST,
	DRIVE_TRAIN_TEST,
	NUDGE, TOTE_LIFT_NUDGE_UP, TOTE_LIFT_NUDGE_DOWN, TOTE_LIFT_RESET, RIGHT_DRIFT, LEFT_DRIFT
}
