package org.usfirst.frc.team1885.robot.common.type;

public enum SensorType {
	LIDAR,
    JOINT_A_POTENTIOMETER,
    JOINT_B_POTENTIOMETER,
    LEFT_ENCODER,
    RIGHT_ENCODER,
    JOYSTICK_LEFT,
    JOYSTICK_RIGHT,
    FLYWHEEL_LEFT_ENCODER,
    FLYWHEEL_RIGHT_ENCODER,
    SHOOTER_TILT_POTENTIOMETER,
    SHOOTER_TWIST_ENCODER,
    DEFENSE_SELECTION, 
    TYPE_2, 
    TYPE_3, 
    TYPE_4, 
    ARM_CTRE_ABSOLUTE, ARM_LIMITER, ARM_LIMITER_BACK, INTAKE_DOWN
}