package org.usfirst.frc.team1885.robot.common.type;

public enum SensorType {
	JOYSTICK_LEFT, JOYSTICK_RIGHT, DRIVE_TRAIN_LEFT_ENCODER, DRIVE_TRAIN_RIGHT_ENCODER, 
	RECYCLE_BIN_ENCODER, RECYCLE_BIN_UPPER_LIMIT, RECYCLE_BIN_LOWER_LIMIT, TOTE_ENCODER, 
	TOTE_UPPER_LIMIT_SWITCH, TOTE_LOWER_LIMIT_SWITCH, LIDAR, LINE_SENSOR, MAGNET_SENSOR,
	TOUCH_SENSOR1, TOUCH_SENSOR2
}