package org.usfirst.frc.team1885.robot.common.type;

public enum SensorType {
    JOYSTICK_LEFT, JOYSTICK_RIGHT,
    LEFT_ENCODER, RIGHT_ENCODER,
    FLYWHEEL_LEFT_ENCODER, FLYWHEEL_RIGHT_ENCODER,
    SHOOTER_TILT_POTENTIOMETER, SHOOTER_TWIST_ENCODER,
    DEFENSE_SELECTION, 
    ARM_CTRE_ABSOLUTE, ARM_LIMITER, ARM_LIMITER_BACK
}